[package]
name = "dexter"
version = "0.1.0"
authors = ["a-yuto <guitarjoepass@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "0.1"
